apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: lil-eks
  region: us-east-2
  tags: 
    project: linkedin-learning

# To pick https://aws.amazon.com/ec2/instance-types/
nodeGroups:
  - name: worker-node
    instanceType: m5.large
    desiredCapacity: 3
